version: '3'   
services:
  mysql:
    image: "mysql:latest"
    container_name: mysqldb
    ports:
     - "3306:3306"
    volumes:
       - ./db-data:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=test
volumes:
    db-data:

    
